accounts:
  - name: user1
    coins: ["1000token", "100000000stake"]
  - name: user2
    coins: ["500token"]
validator:
  name: user1
  staked: "100000000stake"
  
faucet:
  port: 4500
  name: faucet
  coins: ["10000000token"]
  coins_max: ["69token"]
  
# this allows the use of a VPN for edge network nodes
init.config:
  addr_book_strict: false
  
# Build:
#   Proto:
#    path:
#    thirdpartypaths: ["third_party/proto","proto_vendor"]
  
  
# Below are default settings
servers:
  rpc-address: 0.0.0.0:26657
  p2p-address: 0.0.0.0:26656
  prof-address: 0.0.0.0:6060
  grpc-address: 0.0.0.0:9090
  api-address: 0.0.0.0:1317
  frontend-address: 0.0.0.0:8080
  dev-ui-address: 0.0.0.0:12345
