name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: faddat/VuePagesAction@1.0.0
      with:
        username: freewls
        reponame: splash
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        path: vue
